# git actions 이름
name: helloGithubAction

# push가 일어났을 경우 아래 jobs를 실행함
# [push, pull_request]와 같이 다중 이벤트도 처리할 수 있음
on: [push]

# 위 이벤트가 일어났을 경우 실행될 job으로 여러개 설정 가능
jobs:
  # 작업 단위
  build:
    # 실행되는 OS, Window와 Mac OS도 제공됨
    runs-on: ubuntu-latest
    steps:
    # 다른 사람이 만들어놓은 action을 가져오는 것
    # github.com/actions/checkout 폴더를 참고(github에서 만든 것)
    # marketplace에서 여러 uses를 가져올 수 있음
    # 아무것도 없는 OS에서 자동으로 우리의 코드를 클론하고 다운받아 실행하게 해 주는 소스코드
    - uses: actions/checkout@v2
    # name: OS에서 실행할 이름
    # run: OS에서 실행할 명령어
#     - name: 1. 파일 목록 출력
#       run: ls -al
#     - name: 2. 파이썬 패키지 확인
#       run: pip list
    - name: 1. pip 업그레이드
      run: python -m pip install --upgrade pip
    - name: 2. 필요한 패키지 인스톨
      run: pip install -r requirements.txt
    - name: 3. 파이썬 실행
      run: python test.py
    - name: 4. 생성한 일을 커밋하기
      run:
        git config --local user.email "harrykim14@korea.ac.kr"
        git config --local user.name "harrykim14"
        git add .
        git commit -m "Run Crawler and Update current data"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        # branch: "master
        github_token: ${{ secrets.GITHUB_TOKEN }}
